"""CamillaDSP exporter."""

import json
import os

from swproj2eq.core.dsp import compute_preamp_db, freq_response_to_ir_fast, write_wav


def export_camilladsp(channels, outdir, sample_rate=48000, capture_device="swproj2eq_in.monitor", playback_device=""):
    os.makedirs(outdir, exist_ok=True)

    ir_files = []
    for ch in channels:
        ir = freq_response_to_ir_fast(ch.frequencies, ch.correction_dB, sample_rate, 4096)
        fname = f"{ch.name.lower()}_correction.wav"
        fpath = os.path.join(outdir, fname)
        write_wav(fpath, ir, sample_rate)
        ir_files.append(fname)

    for ch in channels:
        txt_path = os.path.join(outdir, f"{ch.name.lower()}_correction.txt")
        with open(txt_path, "w") as f:
            for freq, corr in zip(ch.frequencies, ch.correction_dB):
                f.write(f"{freq:.2f} {corr:.4f}\n")

    preamp_db = compute_preamp_db(channels)
    yaml_lines = [
        "# CamillaDSP config - Sonarworks speaker correction",
        "# Generated by swproj2eq",
        "",
        "devices:",
        f"  samplerate: {sample_rate}",
        "  chunksize: 4096",
        "  capture:",
        "    type: Pulse",
        f"    channels: {len(channels)}",
        f"    device: \"{capture_device}\"",
        "    format: S32LE",
        "  playback:",
        "    type: Pulse",
        f"    channels: {len(channels)}",
        f"    device: \"{playback_device}\"",
        "    format: S32LE",
        "",
        "filters:",
    ]

    for i, ch in enumerate(channels):
        name = ch.name.lower()
        yaml_lines.extend(
            [
                f"  {name}_eq:",
                "    type: Conv",
                "    parameters:",
                f"      filename: \"{ir_files[i]}\"",
                "      type: Wav",
                "      channel: 0",
            ]
        )
        if ch.delay_ms > 0:
            yaml_lines.extend(
                [
                    f"  {name}_delay:",
                    "    type: Delay",
                    "    parameters:",
                    f"      delay: {ch.delay_ms}",
                    "      unit: ms",
                ]
            )

    if preamp_db < 0:
        yaml_lines.extend(
            [
                "  preamp:",
                "    type: Gain",
                "    parameters:",
                f"      gain: {preamp_db:.1f}",
            ]
        )

    yaml_lines.append("")
    yaml_lines.append("pipeline:")

    if preamp_db < 0:
        for i in range(len(channels)):
            yaml_lines.extend(
                [
                    "  - type: Filter",
                    f"    channel: {i}",
                    "    names:",
                    "      - preamp",
                ]
            )

    for i, ch in enumerate(channels):
        names = [f"{ch.name.lower()}_eq"]
        if ch.delay_ms > 0:
            names.append(f"{ch.name.lower()}_delay")
        yaml_lines.extend(["  - type: Filter", f"    channel: {i}", "    names:"])
        for n in names:
            yaml_lines.append(f"      - {n}")

    yaml_path = os.path.join(outdir, "camilladsp.yml")
    with open(yaml_path, "w") as f:
        f.write("\n".join(yaml_lines) + "\n")

    summary = {"source": "Sonarworks SoundID Reference (.swproj)", "channels": []}
    for ch in channels:
        summary["channels"].append(
            {
                "name": ch.name,
                "index": ch.index,
                "group": ch.group,
                "delay_ms": ch.delay_ms,
                "freq_range": [round(ch.frequencies[0], 2), round(ch.frequencies[-1], 2)],
                "correction_range_dB": [round(min(ch.correction_dB), 2), round(max(ch.correction_dB), 2)],
            }
        )

    with open(os.path.join(outdir, "profile_info.json"), "w") as f:
        json.dump(summary, f, indent=2)

    return {
        "config_path": yaml_path,
        "preamp_db": preamp_db,
        "sample_rate": sample_rate,
        "capture_device": capture_device,
        "playback_device": playback_device,
    }
